created putback option
Clever/http-science pull request #45
Opened 2017-03-31 20:47 UTC by Christopher-Bradshaw

2017-03-31 20:52 UTC, Christopher-Bradshaw commented on finalize/finalize.go
> +func LogResults(startTime time.Time, payload *config.Payload) error {
This is just copy pasted out of main except for the stuff re putback at the end

2017-03-31 20:53 UTC, Christopher-Bradshaw commented on finalize/email.go
> +package finalize
Copy pasted out of the email package

2017-03-31 20:53 UTC, Christopher-Bradshaw commented on finalize/error.go
> +package finalize
copy pasted out of config.

2017-03-31 21:17 UTC, Christopher-Bradshaw commented on finalize/finalize.go
> +func LogResults(startTime time.Time, payload *config.Payload) error {
Copy pasted out of main except for the last piece about putbacks

2017-03-31 22:38 UTC, kshen0 commented
LGTM

2017-04-01 02:54 UTC, kvigen commented on finalize/finalize.go
> +		req, err := http.NewRequest(http.MethodPut, payload.PutbackURL, bytes.NewReader(b))
out of curiosity, why put instead of post?

2017-05-24 22:35 UTC, Christopher-Bradshaw commented on finalize/finalize.go
> +		req, err := http.NewRequest(http.MethodPut, payload.PutbackURL, bytes.NewReader(b))
I never really know which of those two to use. . .

2023-04-25 20:47 UTC, kshen0 requested changes
I can't find a way in the Github UI to unassign myself from this but it seems likely this PR should be closed?

2023-04-25 23:10 UTC, schimmy commented
No @kshen0 this PR must be forever preserved to remember this beautiful moment in time! 😛

2023-04-26 01:00 UTC, Christopher-Bradshaw commented
I think it has served its purpose :) I'll close to help @kshen0 get to github inbox 0. Hope you're all doing well!

2023-04-26 01:00 UTC, closed without merging